export const CAREERS = [
  'Administración de Empresas',
  'Administración de Negocios Internacionales',
  'Administración Hotelera y Turismo',
  'Administración y Negocios Digitales',
  'Agronomía y Negocios',
  'Arquitectura de Interiores',
  'Arquitectura y Urbanismo Ambiental',
  'Artes Escénicas',
  'Biología Marina',
  'Comunicación Audiovisual',
  'Comunicación Estratégica y Publicidad Digital',
  'Comunicación y Marketing',
  'Contabilidad y Finanzas',
  'Derecho',
  'Diseño Profesional de Interiores',
  'Educación Inicial',
  'Educación Primaria',
  'Enfermería',
  'Estomatología / Odontología',
  'Farmacia y Bioquímica',
  'Ingeniería Ambiental',
  'Ingeniería Biomédica',
  'Ingeniería Civil',
  'Ingeniería de Minas',
  'Ingeniería de Sistemas de Información',
  'Ingeniería de Software',
  'Ingeniería Económica y de Negocios',
  'Ingeniería Electrónica',
  'Ingeniería Empresarial y de Sistemas',
  'Ingeniería en Ciberseguridad',
  'Ingeniería en Diseño e Innovación Tecnológica',
  'Ingeniería en Inteligencia Artificial y Ciencia de Datos',
  'Ingeniería Industrial',
  'Marketing y Administración',
  'Medicina Humana',
  'Medicina Veterinaria y Zootecnia',
  'Nutrición y Dietética',
  'Obstetricia',
  'Psicología',
  'Relaciones Internacionales y Ciencias Políticas',
  'Traducción e Interpretación'
];

export const AVATARS = ['👻', '👽', '🤖', '🦊', '🦉', '🐱', '🦕', '🦦'];
